-- Voice interview mode support.
-- Adds voice-mode tracking to sessions, transcript + dynamic-question tracking to answers,
-- and a new table for dynamically generated voice interview questions.

-- ── interview_sessions: session mode, topic map, turn tracking ──────────────

ALTER TABLE interview_sessions
    ADD COLUMN mode           VARCHAR(10) NOT NULL DEFAULT 'TEXT'
        CHECK (mode IN ('TEXT', 'VOICE')),
    ADD COLUMN topic_map_json TEXT,
    ADD COLUMN total_turns    INT,
    ADD COLUMN max_turns      INT;

-- ── interview_answers: transcript, dynamic-question flag, per-turn assessment ──

ALTER TABLE interview_answers
    ADD COLUMN transcript            TEXT,
    ADD COLUMN is_dynamic            BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN turn_assessment_json  TEXT;

-- question_id was NOT NULL — drop the constraint so voice answers can omit it
ALTER TABLE interview_answers
    ALTER COLUMN question_id DROP NOT NULL;

-- ── voice_interview_questions: questions generated by Claude per turn ────────

CREATE TABLE voice_interview_questions (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id  UUID        NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
    turn_index  INT         NOT NULL,
    question    TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_voice_questions_session ON voice_interview_questions(session_id);

-- FK from interview_answers to the dynamically generated question (nullable)
ALTER TABLE interview_answers
    ADD COLUMN voice_question_id UUID
        REFERENCES voice_interview_questions(id) ON DELETE SET NULL;
